const Data = [
    {
        id: 1,
        name: "Madhav",
        image: "/petBanner.jpg",
        category: "Dog",
        gender: "male",
        age: "10 months",
        location: "CGC",
        description: "This is madhav(street dog).",
        fwc: "Yes",
        breed: "Street Dog",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: "/5508800.jpg",
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        sterillzed: "Yes",
    }
]

export default Data;